spring:
  application:
    name: library
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  data:
    rest:
      default-media-type: application/json
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}/${POSTGRES_DB_NAME}}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
  sql:
    init:
      mode: never
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/data
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  logging:
    level:
      root: debug
  file:
    name: ../logs/hw.log

cors:
  urls: ${CORS_URLS}

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET_NAME}
  image-size: 10485760
  file-size: 1073741824



