server:
  port: 8686
spring:
  application:
    name: library
  data:
    rest:
      default-media-type: application/json
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5455/library
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/data
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  messages:
    baseName: messages
    encoding: UTF-8
    fallbackToSystemLocale: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:5443/realms/library
    client:
      registration:
        keycloak:
          client-id: otus_library
          client-secret: r2bQaOxF6jKMlvPYVLWvMt2llY69bP26
          authorization-grant-type: authorization_code
          scope: openid-connect
      provider:
        keycloak:
          issuer-uri: http://localhost:5443/realms/library
          user-name-attribute: preferred_username
logging:
  logging:
    level:
      root: debug
  file:
    name: ../logs/hw.log

cors:
  urls: http://localhost:3000

defaults:
  locale: ru-RU

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin123
  bucket-name: library
  image-size: 10485760
  file-size: 104857600



