
FROM node:22.17.0-alpine3.21 AS build
 
WORKDIR /app

COPY ui/package.json ui/yarn.lock /app/
RUN yarn install
COPY ui /app
RUN yarn build

FROM nginx:1.29-alpine3.22
 
COPY --from=build /app/dist /usr/share/nginx/html
COPY ui/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]